#!/bin/bash


set -euo pipefail
IFS=$'\n\t'

# Regex to match the ticket ID at the beginning of the commit message
regex='^[A-Z]+-[0-9]+ '

# Make sure a file is passed as an argument to the script
if [ -z "$1" ]; then
    echo "No commit message file passed. Aborting commit."
    exit 1
fi

# Read the commit message
commit_msg=$(cat "$1")

echo "commit-msg run, got ${commit_msg}"

# Check if the commit message matches the regex
if [[ ! $commit_msg =~ $regex ]]; then
    echo "Your commit message must start with a JIRA ID (e.g., XXX-123:), got: ${commit_msg}"
    exit 1
fi

exit 0