---
  name: Projen Python template CI tests
  on: [push]
  jobs:
    run-format-checker:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: |
            python -m venv .venv
            echo ".venv/bin" >> $GITHUB_PATH
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            scripts/ci/run-format-checker
  
    run-style-checker:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: |
            python -m venv .venv
            echo ".venv/bin" >> $GITHUB_PATH
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            scripts/ci/stylecheck
  
    run-type-checker:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: |
            python -m venv .venv
            echo ".venv/bin" >> $GITHUB_PATH
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            scripts/ci/typecheck
  
  
    run-unit-test:
      runs-on: ubuntu-latest
      environment: CI
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - shell: bash
          run: |
            python -m venv .venv
            echo ".venv/bin" >> $GITHUB_PATH
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            scripts/ci/unittests
